<?php
	/** @var \MvcCore\View $this */
	/** @var $users \App\Models\User[] */
?>

<?php if (!$users): ?>
	<h1><?=$title?></h1>
	<p class="no-users-message">No users available.</p>

<?php else: ?>
	<a 
	   class="users-order-link" 
	   href="<?=$orderLinkValue?>"><?=$orderLinkText?></a>

	<h1><?=$title?></h1>

	<div class="users">
		<?php foreach ($users as $user): ?>
			
			<div class="user">
				<?php if ($user->GetAvatarUrl()): ?>
					<img src="<?=$user->GetAvatarUrl()?>" 
							height="30" width="auto" 
							alt="<?=$user->GetUserName()?>" />
				<?php endif; ?>
				<i><?=$this->FormatDate($user->GetCreated())?></i>
				<h2><?=$user->GetFullName()?></h2>
				<table>
					<tbody>
						<tr>
							<td>E-mail:</td>
							<td><?=$user->GetEmail()?></td>
						</tr>
						<tr>
							<td>Website:</td>
							<td><?=$user->GetWebsiteUrl()?></td>
						</tr>
						<tr>
							<td>Login:</td>
							<td><?=$user->GetUserName()?></td>
						</tr>
					</tbody>
				</table>
			</div>

		<?php endforeach ?>
	</div>
<?php endif; ?>