<?php echo $this->RenderBegin(); ?>
	<?php echo $this->RenderErrors(); ?>

	<?php list (
		$hiddenFields, $contentFieldsAndFielsets, $submitFields
	) = $this->RenderContentGetFieldsGroups(); ?>

	<?php foreach ($hiddenFields as $hiddenField): ?>
		<?php echo $hiddenField->Render(); ?>
	<?php endforeach; ?>

	<div class="controls">
		<?php foreach ($contentFieldsAndFielsets as $contentField): ?>
			<div><?php echo $contentField->Render(); ?></div>
		<?php endforeach; ?>
	</div>

	<?php if ($useRecaptcha): ?>
		<script src="https://www.google.com/recaptcha/api.js" async defer></script>
		<div class="g-recaptcha" data-sitekey="<?=$recaptchaSiteKey?>"></div>
	<?php endif; ?>

	<div class="submits">
		<?php foreach ($submitFields as $submitField): ?>
			<?php echo $submitField->Render(); ?>
		<?php endforeach; ?>
	</div>

<?php echo $this->RenderEnd(); ?>