<?php /** @var \MvcCore\View $this */ ?><!DOCTYPE HTML>
<html lang="en-US">
	<head>
		<meta charset="UTF-8" />
		<title><?=$title?></title>
		<base href="<?=$basePath?>" />
		<link rel="shortcut icon" href="<?=$assetUrl('/static/img/favicon.ico')?>" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<script nonce="<?=$nonce?>">var timestamp=+new Date;(function(a,b,c,d,e,f){if(b[c]('Opera'))b=b[d](e,f);if(b[c]('Trident/'))b=b[d](/ rv:([0-9\.]*)\)/g,e+'$1)');a.setAttribute('data-browser',b);a.className=f;})(document.documentElement,navigator.userAgent,'match','replace',' MSIE ','')</script>
		<meta name="author" content="Tom Flidr <tomflidr(at)gmail(dot)com>" />
		<?=$css('fixedHead')?>
		<?=$js('fixedHead')?>
	</head>
	<body>
		<!--[if lt IE 9]><div class="old-browser-warning"><p>Your browser is <b>very</b> old. <br />Please install any actual browser, for example <br /><a href="https://www.google.com/chrome" target="_blank">Google Chrome</a>, <a href="https://www.apple.com/safari" target="_blank">Apple Safari</a> or <a href="https://www.mozilla.org/en/firefox/new" target="_blank">Mozilla Firefox</a>.</p></div><![endif]-->

		<div class="master-container">

			<?php if (isset($user)): ?>
				<?=$signOutForm?>
			<?php else: ?>
				<div class="signin-link"><a href="<?=$url('Index:SignIn')?>">Login</a></div>
			<?php endif; ?>

			<div class="content route-<?=$currentRouteCssClass?>">
				<div class="header">
					<a href="<?=$url('Index:Index')?>">User Registration</a>
					<a href="<?=$url('Users:List')?>">Registered Users</a>
				</div>
				<div class="document">
					<?=$this->GetContent()?>
				</div>
			</div>

		</div>
		
		<?=$js('varFoot')?>
	</body>
</html>
